### ISSUE TITLE
ITBooks 1.0 Roadmap

### ISSUE THREAD

**Issue by x0s3** [x0s3/itbooks#5]
**Required for a first good release**

- [ ] #1 
- [ ] #2 
- [ ] #3 
- [ ] #4

_**Optionals**_
- [ ] Offline favourite books (download book)(custom go function or third party package)
- [ ] Sync data to use it in another device
- [ ] Filters (by: category, size, pages, lang, etc...)
